;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=Content/Localization/Game/Game.manifest
SourcePath=Mods/GameFeatures/SteelWire/Content/Localization/SteelWire
DestinationPath=Mods/GameFeatures/SteelWire/Content/Localization/SteelWire
ManifestName=SteelWire.manifest
ArchiveName=SteelWire.archive
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/SteelWire/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/GameFeatures/SteelWire/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=SteelWire.csv
bConflictReport=true
ConflictReportName=SteelWire_Conflicts.txt

