;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/SteelWire/Content/Localization/SteelWire
DestinationPath=Mods/GameFeatures/SteelWire/Content/Localization/SteelWire
ManifestName=SteelWire.manifest
ArchiveName=SteelWire.archive
CulturesToGenerate=en
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=SteelWire.csv

