;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/SteelWire/Content/Localization/SteelWire
DestinationPath=Saved/Tolgee/Temp/SteelWire
NativeCulture=en
CulturesToGenerate=en
ManifestName=SteelWire.manifest
ArchiveName=SteelWire.archive
PortableObjectName=SteelWire.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

